export const provinceAbbreviations: { [key: string]: string } = {
  alberta: 'AB',
  "british_columbia": 'BC',
  manitoba: 'MB',
  "new_brunswick": 'NB',
  "newfoundland_and_labrador": 'NL',
  "northwest_territories": 'NT',
  "nova_scotia": 'NS',
  nunavut: 'NU',
  ontario: 'ON',
  "prince_edward_island": 'PE',
  quebec: 'QC',
  saskatchewan: 'SK',
  yukon: 'YT',
  usa: 'USA',
};
